name: Triage

on:
  workflow_call: # This makes the workflow reusable by other repositories

jobs:
  handle-commands:
    if: |
      github.event.comment.author_association == 'OWNER' || 
      github.event.comment.author_association == 'MEMBER' || 
      github.event.comment.author_association == 'COLLABORATOR'
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Issue Tools
        uses: ilim-cell/issuetools@v1
